### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by shaw3257** [viewthespace/shapeable#2]
Action > Controller > Config configuration. Options will be merged

Api:
``` Ruby 
class FoosController

acts_as_shapeable path: Serializers:Foo

def index
  render: json: query.includes(shape.eager_loads), serializer: shape
end
```

**Comment by dnasseri** [comment]
This has mostly been addressed. We still need to add support for a config file

**Comment by shaw3257** [comment]
awesome. I'll close this one out.
