### ISSUE TITLE
Doesn't work if 'Accept' header isn't specified

### ISSUE THREAD

**Issue by ynnadkrap** [viewthespace/shapeable#24]
This occurs in controller specs that don't specify an accept header. Maybe we should default to application/json instead of bailing out?

**Comment by CharlesMcMillan** [comment]
Good catch...I wonder if it could be a configuration option? Like Shapeable.config = {default_accept: 'application/json'} ?

**Comment by dnasseri** [comment]
I don't think we wan't shapeable to be modifying the accept header, something about that seems smelly to me. Maybe instead, we just don't bail out when we encounter a null accept header and instead use the default shape.
